FROM node:5.4.1

COPY package.json /tmp/
COPY bower.json /tmp/

# init workspace
RUN mkdir /workspace
WORKDIR /workspace

# env var fixes excessive npm log output
# see https://github.com/nodejs/docker-node/issues/57
ENV NPM_CONFIG_LOGLEVEL="warn"

RUN cd /tmp; \
  npm install && \
  ./node_modules/.bin/bower install && \
  rm -rf node_modules bower_components package.json bower.json

CMD npm run build
