import avatar from './avatar';
import avatarList from './avatar-list';
import comment from './comment/index';
import discussionThreadView from './discussion-thread-view/index';
import document from './document/index';
import documentNew from './document-new/index';
import extensionButtons from './extension-buttons/index';
import feedbackButton from './feedback-button';
import hiveButton from './hive-button';
import hivedDocs from './hived-docs';
import inlineEditable from './inline-editable/index';
import login from './login/index';
import marginLink from './margin-link';
import marginDiscussion from './margin-discussion/index';
import marginDiscussionDraft from './margin-discussion-draft/index';
import navbar from './navbar/index';
import navbarSearch from './navbar-search/index';
import navbarUser from './navbar-user/index';
import newReply from './new-reply/index';
import notifications from './notifications/index';
import officeMap from './office-map';
import passwordRequest from './passwordRequest';
import passwordReset from './passwordReset';
import searchResults from './search-results/index';
import settings from './settings/index';
import settingsAccounts from './settings-accounts';
import settingsEmail from './settings-email';
import signup from './signup/index';
import subscribe from './subscribe/index';
import user from './user/index';

export default function(app) {
  avatar(app);
  avatarList(app);
  comment(app);
  discussionThreadView(app);
  document(app);
  documentNew(app);
  extensionButtons(app);
  feedbackButton(app);
  hiveButton(app);
  hivedDocs(app);
  inlineEditable(app);
  login(app);
  marginLink(app);
  marginDiscussion(app);
  marginDiscussionDraft(app);
  navbar(app);
  navbarSearch(app);
  navbarUser(app);
  newReply(app);
  notifications(app);
  officeMap(app);
  passwordRequest(app);
  passwordReset(app);
  searchResults(app);
  settings(app);
  settingsAccounts(app);
  settingsEmail(app);
  signup(app);
  subscribe(app);
  user(app);
};
