apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev-frontend
  name: "frontend-$PAPERHIVE_BRANCH-ingress"
  labels:
    name: frontend
    branch: "$PAPERHIVE_BRANCH"
    commit: "$PAPERHIVE_COMMIT"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: dev.paperhive.org
    http:
      paths:
      - path: "/frontend/$PAPERHIVE_BRANCH"
        backend:
          serviceName: "frontend-$PAPERHIVE_BRANCH-service"
          servicePort: 80
