'use strict';
module.exports = function(app) {
  require('./activity.js')(app);
  require('./article.js')(app);
  require('./articleSettings.js')(app);
  require('./articleText.js')(app);
  require('./articleNew.js')(app);
  require('./comment')(app);
  require('./contact')(app);
  require('./discussion.js')(app);
  require('./discussionList.js')(app);
  require('./meta.js')(app);
  require('./help.js')(app);
  require('./jobs.js')(app);
  require('./navbar.js')(app);
  require('./navbarSearch.js')(app);
  require('./navbar_user.js')(app);
  require('./notifications.js')(app);
  require('./oauthOrcid.js')(app);
  require('./settings.js')(app);
  require('./user.js')(app);
  require('./userArticles.js')(app);
  require('./welcome.js')(app);
};
