import activity from './activity';
import article from './article';
import articleSettings from './articleSettings';
import articleText from './articleText';
import articleNew from './articleNew';
import comment from './comment';
import contact from './contact';
import discussion from './discussion';
import discussionList from './discussionList';
import meta from './meta';
import help from './help';
import jobs from './jobs';
import login from './login';
import navbar from './navbar';
import navbarSearch from './navbarSearch';
import navbar_user from './navbar_user';
import notifications from './notifications';
import oauthOrcid from './oauthOrcid';
import settings from './settings';
import signup from './signup'
import subscribe from './subscribe';
import user from './user';
import welcome from './welcome';

export default function(app) {
  activity(app);
  article(app);
  articleSettings(app);
  articleText(app);
  articleNew(app);
  comment(app);
  contact(app);
  discussion(app);
  discussionList(app);
  meta(app);
  help(app);
  jobs(app);
  login(app);
  navbar(app);
  navbarSearch(app);
  navbar_user(app);
  notifications(app);
  oauthOrcid(app);
  settings(app);
  signup(app);
  subscribe(app);
  user(app);
  welcome(app);
};
