import activity from './activity';
import document from './document';
import documentSettings from './documentSettings';
import documentText from './documentText';
import documentNew from './documentNew';
import authReturn from './authReturn';
import comment from './comment';
import contact from './contact';
import discussion from './discussion';
import discussionList from './discussionList';
import meta from './meta';
import help from './help';
import jobs from './jobs';
import login from './login';
import navbar from './navbar';
import navbarSearch from './navbarSearch';
import navbar_user from './navbar_user';
import notifications from './notifications';
import settings from './settings';
import signup from './signup';
import stars from './stars';
import subscribe from './subscribe';
import user from './user';

export default function(app) {
  activity(app);
  document(app);
  documentSettings(app);
  documentText(app);
  documentNew(app);
  authReturn(app);
  comment(app);
  contact(app);
  discussion(app);
  discussionList(app);
  meta(app);
  help(app);
  jobs(app);
  login(app);
  navbar(app);
  navbarSearch(app);
  navbar_user(app);
  notifications(app);
  settings(app);
  signup(app);
  stars(app);
  subscribe(app);
  user(app);
};
